server:
  port: 8180

eureka:
  instance:
    hostname: taskgateway
  client:
    registerWithEureka: true
    fetchRegistry: false
    preferIpAddress: false
    serviceUrl:
      defaultZone: http://taskserver:8761/eureka/


spring:
  application:
    name: taskgateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: route_to_service_1
          uri: http://taskservice1:8080
          predicates:
            - Path=/service1
          filters:
            - RewritePath=/service1, /web/admin

        - id: route_to_service_2
          uri: http://taskservice2:8080
          predicates:
            - Path=/service2
          filters:
            - RewritePath=/service2, /web/home

        - id: route_to_service_3
          uri: http://taskservice3:8080
          predicates:
            - Path=/service3
          filters:
            - RewritePath=/service3, /web/login

management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
    info:
      enabled: true
      app:
        name: 'gateway'
        version: '0.0.5'
        description: 'gateway for task services'
  endpoints:
    web:
      exposure:
        include: '*'